### ISSUE TITLE
Getting IO inside event loop errors in HA logfile

### ISSUE THREAD

**Issue by bkvargyas** [sbabcock23/hass-tryfi#17]
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 9:34:45 AM (6 occurrences)
Last logged: 9:34:45 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tryfi doing I/O at custom_components/tryfi/__init__.py, line 39: tryfi = PyTryFi(username=entry.data["username"], password=entry.data["password"])

I've seen these types of errors before with other custom components.  I know the HA developer team has been trying to force everyone to do do async IO outside the main event loop for performance reasons.

This is with HA core version 2021.1.4

**Comment by sdonoghu75** [comment]
I am getting the same issue.

**Comment by mikewren** [comment]
Just received this issue as well:

Logger: homeassistant.util.async_
Source: util/async_.py:129 
First occurred: 10:21:26 AM (6 occurrences) 
Last logged: 10:21:27 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for tryfi doing I/O at custom_components/tryfi/__init__.py, line 39: tryfi = PyTryFi(username=entry.data["username"], password=entry.data["password"])

Home Assistant 2021.2.1

Thanks for this otherwise terrific integration! Great to see the doggo listed along with the humans in our house. Really looking forward to turning on and off the collar light automagically during night walks - a glaring feature omission in the default app.

**Comment by sbabcock23** [comment]
Thanks for reporting the issue @mikewren, @sdonoghu75 and @bkvargyas. I have fixed the code so you should no longer get this WARNING. Version 0.0.4 has been released.
