### ISSUE TITLE
TryFi Integration Not Loading Any Devices or Entities

### ISSUE THREAD

**Issue by tjsansone** [sbabcock23/hass-tryfi#37]
I have the Fi 2.0 dog collar. When I installed TryFi a couple months ago, the entities never got created. I played around with pytryfi but didn't have any luck (not too experienced with GraphQL) and so this ended up on my backlog.

However I have since completely removed TryFi integration from HACS, restarted, installed latest TryFi integration in HACS, and restarted again... And then when I add the integration by entering my email and password, leaving polling at 10, the install appears successful and no errors are reported in the log.

And yet even now (48 hours later), there are still no entities or devices, despite reloading the integration and restarting HASS multiple times.

When I open my Fi app on my iPhone (iOS 14), everything looks fine. I can track my dog's location, battery, turn on/off the light, track activity, etc. So I'm at a loss as to what I'm missing.

Any ideas on what I should try next?

Thanks!

**Comment by tjsansone** [comment]
@sbabcock23 Can I ask if you're using Fi Collar 1 or 2?

Trying to figure out why I'm not getting anything back from the GraphQL requests even though properly authenticated...

**Comment by sbabcock23** [comment]
Hi @sans-1 ,

I'm using the original series 1 collar. If you turn on debug are you getting any additional details?

**Comment by FinestDice17** [comment]
I have series 2 and its been 48 hrs sense my integration installed with no errors and im also not seeing any entities or devices either.

**Comment by sbabcock23** [comment]
@FinestDice17 can you enable debugging and share the logs related to hass-tryfi or pytryfi?

**Comment by FinestDice17** [comment]
> @FinestDice17 can you enable debugging and share the logs related to hass-tryfi or pytryfi?

@sbabcock23  ive got it working. I was diving into the files under the custom_integrations directory and found a prerequisite (pytryfi) after you said it in your last comment. I then researched it and installed that and restarted everything and everything works fine now. Im not sure if there is a way to update the description for others because no where does it clearly state that you have to do that pytryfi thing unless you dig into files and find it. If it does then I apologize, im just clearly blind.

**Comment by sbabcock23** [comment]
Closing issue. User says its working.
