### ISSUE TITLE
Home Status without GPS?

### ISSUE THREAD

**Issue by ds-sebastian** [sbabcock23/hass-tryfi#47]
Hi,

What still parts of the integration still function without a GPS cellular subscription?

More specifically, is a home status available (perhaps collar connected to base station) without the subscription?

**Comment by sbabcock23** [comment]
Honestly I'm not sure. I don't have a collar without a subscription. I believe it will still work if it's connected to the base or a phone.

**Comment by NathanVanCleave** [comment]
My subscription lapsed a few days ago and I'm happy to report the integration still seems to be working great! 

I can still see its connections status and even location if it's in one of the specified "Safe Zones" otherwise it just says "Unknown." Most importantly, for me, is that I can see see the activity. Even when on walks I can watch the numbers change in HA (as long as it's connected to my phone).
