### ISSUE TITLE
Only two entities populating

### ISSUE THREAD

**Issue by Hunter-Clipper** [sbabcock23/hass-tryfi#76]
Hello,

Logging in works great but the entities only get the Tracker and Lost Mode.
Here is my error log: https://pastebin.com/VC81UFvL
I see some errors in there that make sense, just not 100% on how to remedy the issue.
Here are some screenshots: https://imgur.com/a/bALV1As

I noticed this happened within 24 hours or so.
Troubleshooting: Restarted everything, updated HA and TryFi, even removed TryFi and deleted the config and reinstalled and ensure the config folder was brand new and intact, and then re-logged but same issue.

Any help is appreciated, thank you very much.

PS: Please let me know if I submitted this request wrong :)

**Comment by prestomation** [comment]
Did this work before 0.23 or is this the first time you are using this integration?

**Comment by Hunter-Clipper** [comment]
> Did this work before 0.23 or is this the first time you are using this integration?

Yes it did, it worked on 0.21 and while on .21 it stopped working (within the last 24 hours or so).
So I thought I would update it but even on .23 it still isn't working.

**Comment by prestomation** [comment]
I'm a new contributor to this integration as of this week and contributed the changes to .22 and .23. Since you experienced issues before the upgrade then this must not be related.

Has anything changed with your Fi setup? Any chance you have a new Dog in your Fi household without a collar or with a collar that isn't setup or something like that?

You may add the following to your HA config and restart to get additional logs, this may help:
```
logger:
  logs:
    custom_components.tryfi: debug
    pytryfi: debug
```

please note that this will include things like your dogs GPS location, your name, your phone number/etc so please scrub these out before sharing. It will print a lot of data every few seconds so I suggest adding the debug, restarting HA, copying the log when the error occurs, then remove the log config and restart again.

**Comment by Hunter-Clipper** [comment]
> Has anything changed with your Fi setup? Any chance you have a new Dog in your Fi household without a collar or with a collar that isn't setup or something like that?

Wow... I'm stupid, I had a dog that wasn't set up properly, I removed that dog and it's working just fine now after a "Reload".
This reminded me that when I was at my parents house for Christmas I was helping my parents set up a new collar for them and I still had her collar half set up on my account... 
I am sorry to bother everyone but I thank you for mentioning this cause it pointed me in the right direction!
Uhg, thanks everyone and have a happy new year!

**Comment by prestomation** [comment]
Not stupid, ideally the integration should be able to deal with this. I tried to replicate this and could not with a pet without a collar.  I think the half-setup collar must be the issue but I'm not sure how to replicate this without an actual collar
